import BaseGame from '../../contracts/BaseGame.js';
import { COLLISION_LAYERS } from '../../shared/collision/CollisionLayers.js';
import InteractionPrompt from '../../shared/interaction/ui/InteractionPrompt.js';
import { ROLE_PLAY_CONFIG } from './config/RolePlayConfig.js';
import RolePlayContentRegistry from './content/RolePlayContentRegistry.js';
import RolePlaySession from './core/RolePlaySession.js';
import DialogueEngine from './dialogue/DialogueEngine.js';
import EquipmentSystem from './inventory/EquipmentSystem.js';
import InventorySystem from './inventory/InventorySystem.js';
import ItemRegistry from './inventory/ItemRegistry.js';
import JobSystem from './jobs/JobSystem.js';
import { ROLE_PLAY_CAFE_MAP } from './maps/RolePlayCafeMap.js';
import RolePlayBrain from './npc/RolePlayBrain.js';
import ScheduleSystem from './npc/ScheduleSystem.js';
import RolePlaySaveStore from './persistence/RolePlaySaveStore.js';
import { createRolePlaySaveState, createRolePlaySnapshot } from './protocol/RolePlayProtocol.js';
import QuestSystem from './quests/QuestSystem.js';
import RelationshipSystem from './relationships/RelationshipSystem.js';
import RolePlayRenderer from './render/RolePlayRenderer.js';
import RolePlayHud from './ui/RolePlayHud.js';

const PLAYER_ID='player';
const normalize=(x,z)=>{const l=Math.hypot(x,z);return l>.0001?{x:x/l,z:z/l}:{x:0,z:0};};
export default class RolePlayGame extends BaseGame{
 constructor(){super();this.context=null;this.map=ROLE_PLAY_CAFE_MAP;this.config=ROLE_PLAY_CONFIG;this.content=new RolePlayContentRegistry();this.session=null;this.items=null;this.inventory=null;this.equipment=null;this.relationships=null;this.jobs=null;this.quests=null;this.dialogue=null;this.schedule=null;this.saveStore=null;this.renderer=null;this.hud=null;this.collisionScope=null;this.navigationScope=null;this.interactionScope=null;this.interactionPrompt=null;this.navigationGrid=null;this.world=null;this.interactionActorId=null;this.autosave=0;this.paused=false;this.disposed=false;this.interactableRefs=new Map();this.unsubscribe=[];}
 async preload(context){context.eventBus.emit('role-play:preload',{progress:100,dialogues:this.content.dialogues.length,quests:this.content.quests.length,items:this.content.items.length});}
 async enter(context){this.context=context;this.collisionScope=context.services.collision.createScope('role-play');this.navigationScope=context.services.navigation.createScope('role-play');this.interactionScope=context.services.interaction.createScope('role-play');this.interactionActorId=`${this.interactionScope.owner}:player`;this.setupSpatialWorld();this.setupSystems();this.renderer=new RolePlayRenderer(context,this.map);this.hud=new RolePlayHud({root:context.root,animation:context.animation,itemRegistry:this.items,onPause:()=>context.app.pauseGame(),onChoice:(id)=>this.chooseDialogue(id),onDialogueClose:()=>this.closeDialogue(),onEquip:(id)=>this.equipItem(id)});this.hud.mount();this.interactionPrompt=new InteractionPrompt({root:context.root,eventBus:context.eventBus,actorId:this.interactionActorId});this.interactionPrompt.mount();this.applySettings(context.settings.snapshot());this.resize();}
 setupSpatialWorld(){const statics=this.map.staticColliders.map((d)=>this.collisionScope.addStaticAabb(d.id,d.position,d.halfExtents,{layer:COLLISION_LAYERS.WORLD,mask:COLLISION_LAYERS.CHARACTER,userData:{kind:'role-play-world',definition:d}}));this.navigationGrid=this.navigationScope.createGrid('role-play-cafe',{...this.map.bounds,cellSize:.72,allowDiagonal:true});this.navigationGrid.rasterizeColliders(statics,{padding:this.config.player.radius+.08});}
 setupSystems(){this.items=new ItemRegistry(this.content.items);this.inventory=new InventorySystem({registry:this.items,capacity:this.config.inventory.capacity,onChange:(event)=>this.context.eventBus.emit('role-play:inventory',event)});this.equipment=new EquipmentSystem({inventory:this.inventory,registry:this.items});this.relationships=new RelationshipSystem({tiam:0,ronak:0,amirreza:0});this.jobs=new JobSystem({definitions:this.content.jobs,onEvent:(event)=>this.context.eventBus.emit('role-play:job',event)});this.jobs.unlock('cafe');this.quests=new QuestSystem({definitions:this.content.quests,rewardHandler:(rewards,meta)=>this.applyRewards(rewards,meta),onEvent:(event)=>this.onQuestEvent(event)});this.schedule=new ScheduleSystem(this.content.schedules);this.session=new RolePlaySession({startMinute:this.config.world.startMinute});this.saveStore=new RolePlaySaveStore();const dialogueContext={flags:this.session.flags,variables:this.session.variables,inventory:this.inventory,relationships:this.relationships,quests:this.quests,jobs:this.jobs,emit:(event,payload)=>this.handleDialogueEmit(event,payload)};this.dialogue=new DialogueEngine({definitions:this.content.dialogues,context:dialogueContext,onEvent:(event)=>this.onDialogueEvent(event)});}
 async startSession(params={}){this.clearSessionWorld();this.setupWorld();if(params.newGame===true)this.saveStore.clear();const saved=params.newGame===true?null:this.saveStore.load();if(saved)this.restore(saved);else{this.quests.start('meet-the-team');this.inventory.addCoins(40);}await this.consumeStoryJournal();this.paused=false;this.autosave=0;this.hud.setPaused(false);this.updateUi();this.context.eventBus.emit('role-play:session-started',{resumed:Boolean(saved),snapshot:this.snapshot()});}
 setupWorld(){const player={id:PLAYER_ID,position:{...this.map.spawn},forward:{x:0,z:-1},color:0x67e8f9};this.collisionScope.addDynamicCircle(PLAYER_ID,player.position,this.config.player.radius,{layer:COLLISION_LAYERS.CHARACTER,mask:COLLISION_LAYERS.WORLD|COLLISION_LAYERS.TRIGGER,userData:{kind:'role-play-player'}});const npcs=new Map(this.map.npcs.map((d)=>{const actor={...d,position:{...d.position},forward:{x:0,z:1},activity:'idle'};actor.brain=new RolePlayBrain({npcId:d.id,navigationGrid:this.navigationGrid,speed:this.config.npc.speed});this.collisionScope.addDynamicCircle(`npc-${d.id}`,actor.position,this.config.npc.radius,{layer:COLLISION_LAYERS.CHARACTER,mask:COLLISION_LAYERS.WORLD,userData:{kind:'role-play-npc',npcId:d.id}});return[d.id,actor];}));this.world={player,npcs,collectedPickups:new Set(this.session.variables.collectedPickups??[]),reachedZones:new Set(this.session.variables.reachedZones??[])};this.registerInteractions();}
 clearSessionWorld(){if(!this.world)return;try{this.collisionScope.remove(PLAYER_ID);}catch{}for(const npc of this.map.npcs){try{this.collisionScope.remove(`npc-${npc.id}`);}catch{}}for(const ref of this.interactableRefs.values())this.context.services.interaction.unregister(ref.id);this.interactableRefs.clear();this.context.services.interaction.clearActor(this.interactionActorId);this.world=null;}
 registerInteractions(){for(const npc of this.world.npcs.values()){const ref=this.interactionScope.register({id:`talk-${npc.id}`,position:npc.position,radius:2.35,label:`صحبت با ${npc.name}`,priority:20,action:async()=>this.startDialogue(npc.dialogueId,npc.id)});this.interactableRefs.set(`npc:${npc.id}`,ref);}for(const pickup of this.map.pickups){const collected=this.world.collectedPickups.has(pickup.id);const ref=this.interactionScope.register({id:`pickup-${pickup.id}`,position:pickup.position,radius:1.8,label:`برداشتن ${this.items.get(pickup.itemId).title}`,priority:25,enabled:!collected,action:async()=>this.collectPickup(pickup)});this.interactableRefs.set(`pickup:${pickup.id}`,ref);}for(const entry of this.map.interactables){const action=entry.kind==='delivery'?()=>this.deliverOrder(entry):entry.kind==='repair'?()=>this.repairArcade(entry):()=>this.activateSavePoint(entry);const ref=this.interactionScope.register({id:entry.id,position:entry.position,radius:entry.radius,label:entry.label,priority:18,action});this.interactableRefs.set(`world:${entry.id}`,ref);}}
 async startDialogue(dialogueId,npcId){this.hud.closePanels();await this.dialogue.start(dialogueId);await this.quests.dispatch({type:'talk',target:npcId});this.world.npcs.get(npcId)?.brain.memory.remember('conversation',{dialogueId},3);this.session.status=`در حال گفتگو با ${this.world.npcs.get(npcId)?.name??npcId}`;this.updateUi();return true;}
 async chooseDialogue(choiceId){try{await this.dialogue.choose(choiceId);if(!this.dialogue.active())this.session.status='گفتگو پایان یافت.';this.updateUi();}catch(error){this.context.eventBus.emit('role-play:dialogue-error',{error});}}
 closeDialogue(){this.dialogue.close('player-close');this.session.status='گفتگو بسته شد.';this.updateUi();}

 async consumeStoryJournal(){const journal=this.context.services.storyJournal;if(!journal)return;const cursor=Number(this.session.variables.storyCursor)||0;const entries=journal.since(cursor);for(const entry of entries){if(entry.type==='play')await this.quests.dispatch({type:'play',gameId:entry.payload.gameId});if(entry.type==='win')await this.quests.dispatch({type:'win',gameId:entry.payload.gameId});}this.session.variables.storyCursor=journal.latestCursor();}
 async handleDialogueEmit(event,payload={}){if(event==='quest-event')return this.quests.dispatch(payload);if(event==='launch-game'&&payload.gameId){this.saveProgress('before-game');return this.context.app.launchGame(payload.gameId,{source:'role-play'});}this.context.eventBus.emit(`role-play:${event}`,payload);return true;}
 async collectPickup(pickup){if(this.world.collectedPickups.has(pickup.id))return false;this.inventory.add(pickup.itemId,1);this.world.collectedPickups.add(pickup.id);this.session.variables.collectedPickups=[...this.world.collectedPickups];const ref=this.interactableRefs.get(`pickup:${pickup.id}`);if(ref)this.context.services.interaction.setEnabled(ref.id,false);this.renderer.setPickupVisible(pickup.id,false);await this.quests.dispatch({type:'collect',itemId:pickup.itemId,amount:1});this.hud.announce(`${this.items.get(pickup.itemId).title} اضافه شد`,'success');return true;}
 async deliverOrder(entry){if(!this.inventory.has('coffee-cup',3)){this.hud.announce('سه فنجان قهوه لازم داری','danger');return false;}this.inventory.remove('coffee-cup',3);await this.quests.dispatch({type:'deliver',itemId:'coffee-cup',target:entry.id,amount:3});this.hud.announce('سفارش تحویل شد','success');return true;}
 async repairArcade(entry){if(!this.inventory.has('repair-kit',1)){this.hud.announce('کیت تعمیر را پیدا کن','danger');return false;}this.inventory.remove('repair-kit',1);await this.quests.dispatch({type:'interact',target:entry.id,amount:1});this.session.flags.add('arcade-repaired');this.hud.announce('کابین تعمیر شد','success');return true;}

 activateSavePoint(entry){this.session.variables.lastSavePoint=entry.id;this.session.variables.unlockedAreas=[...new Set([...(this.session.variables.unlockedAreas??[]),'cafe-main'])];return this.saveProgress('manual');}
 async applyRewards(rewards,meta={}){for(const reward of rewards){if(reward.type==='coins')this.inventory.addCoins(reward.amount);if(reward.type==='item')this.inventory.add(reward.itemId,reward.amount??1);if(reward.type==='relationship')this.relationships.adjust(reward.npcId,reward.amount,`quest:${meta.questId}`);if(reward.type==='jobXp')this.jobs.addXp(reward.jobId,reward.amount,`quest:${meta.questId}`);if(reward.type==='flag')this.session.flags.add(reward.key);}this.hud?.announce('پاداش مأموریت دریافت شد','success',2200);this.saveProgress('quest-reward');}
 onQuestEvent(event){if(event.type==='completed')this.session.status=`مأموریت «${event.snapshot.title}» کامل شد.`;this.context.eventBus.emit(`role-play:quest-${event.type}`,event);this.updateUi();}
 onDialogueEvent(event){this.context.eventBus.emit(`role-play:dialogue-${event.type}`,event);this.updateUi();}
 equipItem(itemId){try{const item=this.items.get(itemId);if(!item.equipSlot)return;this.equipment.equip(itemId);this.hud.announce(`${item.title} تجهیز شد`,'success');this.updateUi();}catch(error){this.hud.announce(error.message,'danger');}}
 fixedUpdate(dt,input={}){if(this.paused||!this.world)return;this.session.update(dt,this.config.world.minutesPerSecond);this.autosave+=dt;this.quests.dispatch({type:'wait',seconds:dt}).catch(()=>undefined);if(this.dialogue.active()){if(input.cancelDialogue)this.closeDialogue();}else{if(input.cancelDialogue)this.context.app.pauseGame();this.updatePlayer(dt,input);this.updateInteraction(input);}if(input.toggleInventory)this.hud.toggleInventory();if(input.toggleQuests)this.hud.toggleQuests();if(input.pause)this.context.app.pauseGame();this.updateNpcs(dt);this.updateZones();if(this.autosave>=this.config.world.autosaveSeconds){this.autosave=0;this.saveProgress('autosave');}}
 updatePlayer(dt,input){const x=Number(input.x)||0,z=Number(input.z)||0;const direction=normalize(x,z);const moving=Math.hypot(x,z)>.05;const speed=input.run?this.config.player.runSpeed:this.config.player.walkSpeed;if(moving)this.world.player.forward=direction;const target={x:this.world.player.position.x+direction.x*speed*dt,z:this.world.player.position.z+direction.z*speed*dt};const result=this.collisionScope.moveCircle(PLAYER_ID,target);this.world.player.position=result.position;}
 updateInteraction(input){for(const npc of this.world.npcs.values()){const ref=this.interactableRefs.get(`npc:${npc.id}`);if(ref)ref.position={...npc.position};}this.context.services.interaction.updateActor({actorId:this.interactionActorId,position:this.world.player.position,forward:this.world.player.forward});if(input.interact)this.context.services.interaction.interact(this.interactionActorId,{game:this}).catch((error)=>this.context.eventBus.emit('role-play:interaction-error',{error}));}
 updateNpcs(dt){for(const npc of this.world.npcs.values()){const schedule=this.schedule.resolve(npc.id,this.session.worldTime);if(schedule&&npc.activity!==schedule.activity){npc.activity=schedule.activity;npc.brain.setSchedule(schedule);}const delta=npc.brain.update(npc,dt);if(Math.hypot(delta.x,delta.z)>.0001){npc.forward=normalize(delta.x,delta.z);const result=this.collisionScope.moveCircle(`npc-${npc.id}`,{x:npc.position.x+delta.x,z:npc.position.z+delta.z});npc.position=result.position;}}}
 updateZones(){for(const zone of this.map.zones){if(this.world.reachedZones.has(zone.id))continue;if(Math.hypot(this.world.player.position.x-zone.position.x,this.world.player.position.z-zone.position.z)<=zone.radius){this.world.reachedZones.add(zone.id);this.session.variables.reachedZones=[...this.world.reachedZones];this.quests.dispatch({type:'reach',zone:zone.id}).catch(()=>undefined);}}}
 update(dt){if(!this.world)return;this.renderer.sync(this.world,dt);this.updateUi();}
 render(){this.renderer?.render();}
 snapshot(){return createRolePlaySnapshot({tick:this.session.tick,worldTime:this.session.worldTime,player:this.world?.player,dialogue:this.dialogue.snapshot(),quests:this.quests.snapshot(),inventory:this.inventory.snapshot(),equipment:this.equipment.snapshot(),relationships:this.relationships.snapshot(),jobs:this.jobs.snapshot(),npcs:[...(this.world?.npcs.values()??[])].map((n)=>({id:n.id,name:n.name,position:n.position,activity:n.activity})),flags:this.session.flags,status:this.session.status,session:this.session.snapshot()});}
 updateUi(){if(this.hud&&this.world)this.hud.update({...this.snapshot(),session:this.session.snapshot()});}
 saveProgress(reason='manual'){if(!this.world)return null;const state=createRolePlaySaveState({worldTime:this.session.worldTime,player:this.world.player,flags:this.session.flags,variables:this.session.variables,inventory:this.inventory,equipment:this.equipment,relationships:this.relationships,jobs:this.jobs,quests:this.quests,dialogue:this.dialogue,npcs:this.world.npcs});const saved=this.saveStore.save(state);this.context.eventBus.emit('role-play:saved',{reason,savedAt:saved.savedAt});if(reason==='manual')this.hud.announce('پیشرفت ذخیره شد','success');return saved;}
 restore(state){this.session.import(state);this.inventory.import(state.inventory);this.equipment.import(state.equipment);this.relationships.import(state.relationships);this.jobs.import(state.jobs);this.quests.import(state.quests);this.dialogue.import(state.dialogue);if(state.player?.position){this.world.player.position={...state.player.position};this.collisionScope.sync(PLAYER_ID,this.world.player.position);}for(const[id,entries]of Object.entries(state.npcMemory??{}))this.world.npcs.get(id)?.brain.memory.import(entries);this.world.collectedPickups=new Set(state.variables?.collectedPickups??[]);for(const id of this.world.collectedPickups){this.renderer?.setPickupVisible(id,false);const ref=this.interactableRefs.get(`pickup:${id}`);if(ref)this.context.services.interaction.setEnabled(ref.id,false);}this.session.status='آخرین ذخیره بازیابی شد.';}
 applySettings(settings){const ratios={performance:1,balanced:1.25,high:Math.min(devicePixelRatio||1,2),auto:Math.min(devicePixelRatio||1,1.5)};this.renderer?.setPixelRatio(ratios[settings?.quality]??1);}
 resize(){this.renderer?.resize();}
 pause(){this.paused=true;this.saveProgress('pause');this.hud?.setPaused(true);this.context?.services.interaction.clearActor(this.interactionActorId);}
 resume(){this.paused=false;this.hud?.setPaused(false);}
 async exit(){this.saveProgress('exit');this.context?.services.interaction.clearActor(this.interactionActorId);}
 dispose(){if(this.disposed)return;this.disposed=true;this.clearSessionWorld();this.interactionPrompt?.dispose();this.hud?.dispose();this.renderer?.dispose();this.interactionScope?.dispose();this.navigationScope?.dispose();this.collisionScope?.dispose();this.world=null;this.context=null;}
}
