import { CAFE_ENVIRONMENT_ID, CAFE_REFERENCE_ASSET_ROOT } from '../shared/cafe/CafeEnvironmentContract.js';

export const GAME_CATALOG = Object.freeze([

    Object.freeze({
        id: 'neon-run', title: 'NEON RUN', subtitle: 'Jump · Dash · Survive',
        description: 'رانر دوبعدی سریع با پرش، دش، Combo و سرعت افزایشی.', icon: '»', phase: 9,
        status: 'available', available: true, orientation: 'landscape', accent: 'pink',
        environment: CAFE_ENVIRONMENT_ID, environmentLocked: true, referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'star-catcher', title: 'STAR CATCHER', subtitle: 'Catch Gold · Dodge Red',
        description: 'ستاره‌های طلایی را جمع کن و از بمب‌های قرمز جاخالی بده.', icon: '★', phase: 9,
        status: 'available', available: true, orientation: 'landscape', accent: 'amber',
        environment: CAFE_ENVIRONMENT_ID, environmentLocked: true, referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'cafe-drift', title: 'CAFÉ DRIFT', subtitle: 'Near Miss = Big Score',
        description: 'دریفت آرکیدی بین موانع؛ هر Near Miss ضریب امتیاز را بالا می‌برد.', icon: '◇', phase: 9,
        status: 'available', available: true, orientation: 'landscape', accent: 'cyan',
        environment: CAFE_ENVIRONMENT_ID, environmentLocked: true, referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'shadow-maze', title: 'SHADOW MAZE', subtitle: '5 Keys · One Exit',
        description: 'هزارتوی دوبعدی، پنج کلید، سایه‌های متحرک و یک خروجی مخفی.', icon: '◆', phase: 9,
        status: 'available', available: true, orientation: 'landscape', accent: 'violet',
        environment: CAFE_ENVIRONMENT_ID, environmentLocked: true, referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'sky-hop', title: 'SKY HOP', subtitle: 'Reach 100 Meters',
        description: 'پلتفرمر عمودی سریع؛ روی سکوها بپر و تا ۱۰۰ متر اوج بگیر.', icon: '▲', phase: 9,
        status: 'available', available: true, orientation: 'landscape', accent: 'emerald',
        environment: CAFE_ENVIRONMENT_ID, environmentLocked: true, referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'rhythm-rush', title: 'RHYTHM RUSH', subtitle: 'Jump · Use · Dash',
        description: 'ریتم سه‌لاین با اکشن‌های خود کاراکتر و Combo مبتنی بر دقت.', icon: '♫', phase: 9,
        status: 'available', available: true, orientation: 'landscape', accent: 'pink',
        environment: CAFE_ENVIRONMENT_ID, environmentLocked: true, referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'tetris',
        title: 'TETRIS',
        subtitle: 'Classic Puzzle',
        description: 'چیدمان کلاسیک، رکورد و رقابت روی میز بازی داخل کافه دمیان.',
        icon: '▦',
        phase: 3,
        status: 'available',
        available: true,
        orientation: 'portrait',
        accent: 'cyan',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'hide-and-seek',
        title: 'HIDE & SEEK',
        subtitle: 'Hide. Run. Survive.',
        description: 'پنهان شو، جست‌وجو کن و پیش از پایان زمان برنده شو.',
        icon: '◉',
        phase: 5,
        status: 'available',
        available: true,
        orientation: 'landscape',
        accent: 'pink',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'event',
        title: 'EVENT',
        subtitle: 'Limited-Time Challenges',
        description: 'چالش‌های زمان‌دار، قوانین ویژه و جایزه‌های دوره‌ای.',
        icon: '✦',
        phase: 6,
        status: 'available',
        available: true,
        orientation: 'landscape',
        accent: 'amber',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'role-play',
        title: 'ROLE PLAY',
        subtitle: 'Live Your Story',
        description: 'داستان، انتخاب، دیالوگ، شغل و مأموریت‌های شاخه‌ای در کافه دمیان.',
        icon: '◇',
        phase: 7,
        status: 'available',
        available: true,
        orientation: 'landscape',
        accent: 'violet',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'open-world',
        title: 'OPEN WORLD',
        subtitle: 'Explore Demian Café',
        description: 'کاوش آزاد در کافه دمیان با Chunk Streaming، نقشه، سفر سریع و Save Point.',
        icon: '◫',
        phase: 8,
        status: 'available',
        available: true,
        orientation: 'landscape',
        accent: 'emerald',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
]);

export function findGameCatalogEntry(gameId) {
    return GAME_CATALOG.find((game) => game.id === gameId) ?? null;
}
