import { CAFE_ENVIRONMENT_ID, CAFE_REFERENCE_ASSET_ROOT } from '../shared/cafe/CafeEnvironmentContract.js';

export const GAME_CATALOG = Object.freeze([
    Object.freeze({
        id: 'tetris',
        title: 'TETRIS',
        subtitle: 'Classic Puzzle',
        description: 'چیدمان کلاسیک، رکورد و رقابت روی میز بازی داخل کافه دمیان.',
        icon: '▦',
        phase: 3,
        status: 'available',
        available: true,
        orientation: 'portrait',
        accent: 'cyan',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'hide-and-seek',
        title: 'HIDE & SEEK',
        subtitle: 'Hide. Run. Survive.',
        description: 'پنهان شو، جست‌وجو کن و پیش از پایان زمان برنده شو.',
        icon: '◉',
        phase: 5,
        status: 'available',
        available: true,
        orientation: 'landscape',
        accent: 'pink',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'event',
        title: 'EVENT',
        subtitle: 'Limited-Time Challenges',
        description: 'چالش‌های زمان‌دار، قوانین ویژه و جایزه‌های دوره‌ای.',
        icon: '✦',
        phase: 6,
        status: 'available',
        available: true,
        orientation: 'landscape',
        accent: 'amber',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'role-play',
        title: 'ROLE PLAY',
        subtitle: 'Live Your Story',
        description: 'داستان، انتخاب، دیالوگ، شغل و مأموریت‌های شاخه‌ای در کافه دمیان.',
        icon: '◇',
        phase: 7,
        status: 'available',
        available: true,
        orientation: 'landscape',
        accent: 'violet',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
    Object.freeze({
        id: 'open-world',
        title: 'OPEN WORLD',
        subtitle: 'Explore Demian Café',
        description: 'کاوش آزاد در کافه دمیان با Chunk Streaming، نقشه، سفر سریع و Save Point.',
        icon: '◫',
        phase: 8,
        status: 'available',
        available: true,
        orientation: 'landscape',
        accent: 'emerald',
        environment: CAFE_ENVIRONMENT_ID,
        environmentLocked: true,
        referenceAssets: CAFE_REFERENCE_ASSET_ROOT,
    }),
]);

export function findGameCatalogEntry(gameId) {
    return GAME_CATALOG.find((game) => game.id === gameId) ?? null;
}
