import * as THREE from 'three';
function disposeObject(object){object.traverse?.((child)=>{child.geometry?.dispose?.();if(Array.isArray(child.material))child.material.forEach((m)=>m.dispose?.());else child.material?.dispose?.();});}
function actorMesh(color,isPlayer=false){const group=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.45,.88,5,10),new THREE.MeshStandardMaterial({color,roughness:.66}));body.position.y=.95;const head=new THREE.Mesh(new THREE.SphereGeometry(.32,14,10),new THREE.MeshStandardMaterial({color:0xf4d5c4,roughness:.82}));head.position.y=1.78;const marker=new THREE.Mesh(new THREE.RingGeometry(.56,.66,28),new THREE.MeshBasicMaterial({color:isPlayer?0x67e8f9:color,transparent:true,opacity:isPlayer?.85:.28,side:THREE.DoubleSide}));marker.rotation.x=-Math.PI/2;marker.position.y=.025;group.add(body,head,marker);return group;}
export default class RolePlayRenderer{
 constructor(context,map){this.context=context;this.map=map;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x050816);this.scene.fog=new THREE.FogExp2(0x050816,.018);this.camera=new THREE.PerspectiveCamera(48,1,.1,140);this.camera.position.set(0,18,17);this.actors=new Map();this.pickups=new Map();this.markers=new Map();this.createLighting();this.createMap();this.resize();}
 createLighting(){this.scene.add(new THREE.HemisphereLight(0x9ed8ff,0x160b22,1.45));const key=new THREE.DirectionalLight(0xffe5c8,1.75);key.position.set(-10,20,12);this.scene.add(key);for(const [x,z,color] of [[-12,-5,0xf59e0b],[12,-5,0x8b5cf6],[0,7,0x22d3ee]]){const light=new THREE.PointLight(color,24,18,2);light.position.set(x,4,z);this.scene.add(light);}}
 createMap(){const floor=new THREE.Mesh(new THREE.PlaneGeometry(this.map.floor.width,this.map.floor.depth),new THREE.MeshStandardMaterial({color:this.map.floor.color,roughness:.92,metalness:.02}));floor.rotation.x=-Math.PI/2;this.scene.add(floor);this.map.staticColliders.forEach((d)=>{const h=d.height??2;const mesh=new THREE.Mesh(new THREE.BoxGeometry(d.halfExtents.x*2,h,d.halfExtents.z*2),new THREE.MeshStandardMaterial({color:d.color??0x334155,roughness:.74}));mesh.position.set(d.position.x,h/2,d.position.z);this.scene.add(mesh);});const grid=new THREE.GridHelper(36,36,0x374151,0x111827);grid.position.y=.015;grid.material.transparent=true;grid.material.opacity=.16;this.scene.add(grid);this.map.pickups.forEach((p)=>{const mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.34),new THREE.MeshStandardMaterial({color:p.color,emissive:p.color,emissiveIntensity:.35}));mesh.position.set(p.position.x,.62,p.position.z);this.scene.add(mesh);this.pickups.set(p.id,mesh);});this.map.interactables.forEach((entry)=>{const mesh=new THREE.Mesh(new THREE.RingGeometry(.55,.7,28),new THREE.MeshBasicMaterial({color:0x67e8f9,transparent:true,opacity:.28,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;mesh.position.set(entry.position.x,.03,entry.position.z);this.scene.add(mesh);this.markers.set(entry.id,mesh);});}
 sync(world,dt){const participants=[world.player,...world.npcs.values()];const live=new Set(participants.map((a)=>a.id));for(const[id,mesh]of this.actors)if(!live.has(id)){this.scene.remove(mesh);disposeObject(mesh);this.actors.delete(id);}for(const actor of participants){let mesh=this.actors.get(actor.id);if(!mesh){mesh=actorMesh(actor.color??0x94a3b8,actor.id==='player');this.actors.set(actor.id,mesh);this.scene.add(mesh);}mesh.position.set(actor.position.x,0,actor.position.z);mesh.rotation.y=Math.atan2(actor.forward?.x??0,actor.forward?.z??1);}for(const[id,mesh]of this.pickups){mesh.visible=!world.collectedPickups.has(id);if(mesh.visible)mesh.rotation.y+=dt*1.8;}const player=world.player;const desired=new THREE.Vector3(player.position.x,17.5,player.position.z+15.5);const alpha=1-Math.exp(-4.5*Math.max(0,dt));this.camera.position.lerp(desired,alpha);this.camera.lookAt(player.position.x,0,player.position.z-1.2);}
 setPickupVisible(id,visible){const mesh=this.pickups.get(id);if(mesh)mesh.visible=visible;}
 resize(){const {width,height}=this.context.renderer.resize(this.pixelRatio??1);this.camera.aspect=Math.max(1,width)/Math.max(1,height);this.camera.updateProjectionMatrix();}
 render(){this.context.renderer.renderer.render(this.scene,this.camera);}
 setPixelRatio(value){this.pixelRatio=Math.max(.75,Number(value)||1);this.resize();}
 dispose(){disposeObject(this.scene);this.actors.clear();this.pickups.clear();this.markers.clear();this.scene.clear();}
}
