import { existsSync, readFileSync } from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { testRunnerCoversGroup } from './validation/testRunnerContract.mjs';
import { validateRolePlayContent } from '../resources/js/game/games/role-play/core/RolePlayDefinitionValidator.js';
import { BUILT_IN_ROLE_PLAY_CONTENT } from '../resources/js/game/games/role-play/content/RolePlayContentRegistry.js';
import { walk, lintPhpFiles } from './validation/projectWalk.mjs';

const root = resolve(import.meta.dirname, '..');
const failures = [];
function assert(condition,message){if(!condition)failures.push(message);}
const jsFiles=[...walk(join(root,'resources/js'),(f)=>extname(f)==='.js'),...walk(join(root,'tests/js'),(f)=>extname(f)==='.js'),...walk(join(root,'tools'),(f)=>extname(f)==='.mjs')];
for(const file of jsFiles){const check=spawnSync(process.execPath,['--check',file],{encoding:'utf8'});assert(check.status===0,`Syntax error: ${file}\n${check.stderr}`);const source=readFileSync(file,'utf8');const imports=file.includes(`${join('tools','')}`)?[]:[...source.matchAll(/\bfrom\s+['"]([^'"]+)['"]/g),...source.matchAll(/\bimport\(\s*['"]([^'"]+)['"]\s*\)/g)].map((m)=>m[1]).filter((s)=>s.startsWith('.'));for(const specifier of imports){const base=resolve(dirname(file),specifier);assert([base,`${base}.js`,`${base}.mjs`,`${base}.json`,join(base,'index.js')].some(existsSync),`Unresolved import ${specifier} in ${file}`);}}
const required=[
'resources/js/game/games/role-play/RolePlayGame.js','resources/js/game/games/role-play/content/RolePlayContentRegistry.js','resources/js/game/games/role-play/core/RolePlayDefinitionValidator.js','resources/js/game/games/role-play/core/RolePlaySession.js','resources/js/game/games/role-play/dialogue/DialogueEngine.js','resources/js/game/games/role-play/dialogue/DialogueRunner.js','resources/js/game/games/role-play/dialogue/DialogueCondition.js','resources/js/game/games/role-play/dialogue/DialogueAction.js','resources/js/game/games/role-play/quests/QuestSystem.js','resources/js/game/games/role-play/quests/QuestTracker.js','resources/js/game/games/role-play/inventory/InventorySystem.js','resources/js/game/games/role-play/inventory/ItemRegistry.js','resources/js/game/games/role-play/inventory/EquipmentSystem.js','resources/js/game/games/role-play/relationships/RelationshipSystem.js','resources/js/game/games/role-play/jobs/JobSystem.js','resources/js/game/games/role-play/npc/ScheduleSystem.js','resources/js/game/games/role-play/npc/RolePlayBrain.js','resources/js/game/games/role-play/npc/NpcMemory.js','resources/js/game/games/role-play/persistence/RolePlaySaveStore.js','resources/js/game/games/role-play/protocol/RolePlayProtocol.js','resources/js/game/games/role-play/maps/RolePlayCafeMap.js','resources/js/game/games/role-play/render/RolePlayRenderer.js','resources/js/game/games/role-play/ui/RolePlayHud.js','resources/js/game/games/role-play/ui/DialoguePanel.js','resources/js/game/games/role-play/ui/QuestPanel.js','resources/js/game/games/role-play/ui/InventoryPanel.js','resources/js/game/shared/story/StoryEventJournal.js','docs/PHASE-7-ROLE-PLAY.fa.md'];
required.forEach((file)=>assert(existsSync(join(root,file)),`Missing ${file}`));
const contentErrors=validateRolePlayContent(BUILT_IN_ROLE_PLAY_CONTENT);assert(contentErrors.length===0,`Invalid bundled Role Play content: ${contentErrors.join('; ')}`);assert(BUILT_IN_ROLE_PLAY_CONTENT.dialogues.length>=3,'At least three dialogues required.');assert(BUILT_IN_ROLE_PLAY_CONTENT.quests.length>=3,'At least three quests required.');assert(BUILT_IN_ROLE_PLAY_CONTENT.jobs.length>=3,'At least three jobs required.');
const domainDirs=['content','core','dialogue','inventory','jobs','npc','persistence','protocol','quests','relationships'];for(const file of domainDirs.flatMap((dir)=>walk(join(root,`resources/js/game/games/role-play/${dir}`),(f)=>extname(f)==='.js'))){const source=readFileSync(file,'utf8');assert(!source.includes("from 'three'"),`Role Play domain imports Three.js: ${file}`);assert(!/\b(document|window|HTMLElement|HTMLCanvasElement)\b/.test(source),`Role Play domain depends on DOM: ${file}`);assert(!/\b(TODO|FIXME|debugger|console\.log)\b/.test(source),`Debug marker found: ${file}`);}
const game=readFileSync(join(root,'resources/js/game/games/role-play/RolePlayGame.js'),'utf8');for(const marker of ["createScope('role-play')",'new DialogueEngine','new QuestSystem','new InventorySystem','new RelationshipSystem','new JobSystem','new ScheduleSystem','new RolePlaySaveStore','consumeStoryJournal','new RolePlayBrain','saveProgress'])assert(game.includes(marker),`RolePlayGame integration missing: ${marker}`);
const defs=readFileSync(join(root,'resources/js/game/registry/GameDefinitions.js'),'utf8');for(const marker of ["'role-play': Object.freeze", "inputContext: 'ROLE_PLAY'", "loader: () => import('../games/role-play/RolePlayGame.js')",'dataDrivenDialogue: true','persistentProgress: true'])assert(defs.includes(marker),`Role Play definition missing: ${marker}`);
const catalog=readFileSync(join(root,'resources/js/game/catalog/GameCatalog.js'),'utf8');const section=catalog.slice(catalog.indexOf("id: 'role-play'"),catalog.indexOf("id: 'open-world'"));assert(section.includes("status: 'available'"),'Role Play catalog not available.');assert(section.includes('available: true'),'Role Play catalog not playable.');
const input=readFileSync(join(root,'resources/js/game/input/InputContexts.js'),'utf8');for(const marker of ['ROLE_PLAY: Object.freeze','toggleInventory','toggleQuests','cancelDialogue'])assert(input.includes(marker),`Role Play input missing: ${marker}`);
const controls=readFileSync(join(root,'resources/js/game/controls/ControlLayoutService.js'),'utf8');assert(controls.includes("ROLE_PLAY: Object.freeze({ id: 'role-play', joystick: true })"),'Role Play mobile layout missing.');
const css=readFileSync(join(root,'resources/css/app.css'),'utf8');for(const marker of ['.role-play-hud','.role-play-dialogue','.role-play-side-panel','data-control-layout="role-play"'])assert(css.includes(marker),`Role Play CSS missing: ${marker}`);const stripped=css.replace(/\/\*[\s\S]*?\*\//g,'');assert((stripped.match(/{/g)??[]).length===(stripped.match(/}/g)??[]).length,'CSS braces unbalanced.');
const packageJson=JSON.parse(readFileSync(join(root,'package.json'),'utf8'));assert(packageJson.scripts?.['validate:phase7']==='node tools/validate_phase7.mjs','validate:phase7 script missing.');assert(testRunnerCoversGroup(root,packageJson,'role-play'),'Role Play tests omitted.');
const workflow=readFileSync(resolve(root,'../.github/workflows/deploy-demian-pages.yml'),'utf8');assert(workflow.includes('npm run validate:phase7'),'CI does not run validate:phase7.');
const lock=readFileSync(join(root,'package-lock.json'),'utf8');assert(!/mirror-npm|runflare/i.test(lock),'package-lock references private mirror.');
const phpFiles=lintPhpFiles(root,assert);
if(failures.length){console.error(`Phase 7 validation failed (${failures.length}):`);failures.forEach((f)=>console.error(`- ${f}`));process.exit(1);}console.log(`Phase 7 source validation passed: ${jsFiles.length} JavaScript/MJS, ${phpFiles.length} PHP, ${BUILT_IN_ROLE_PLAY_CONTENT.dialogues.length} dialogues and ${BUILT_IN_ROLE_PLAY_CONTENT.quests.length} quests checked.`);
