function frozenObjective(definition,state){const target=Math.max(1,Number(definition.amount)||1);return Object.freeze({id:definition.id,type:definition.type,title:definition.title??definition.id,target,progress:Math.min(target,state.progress??0),complete:Boolean(state.complete),unlocked:Boolean(state.unlocked)});}
export default class QuestTracker{
 constructor(definition){this.definition=definition;this.status='active';this.startedAt=Date.now();this.completedAt=null;this.objectives=new Map(definition.objectives.map((o)=>[o.id,{progress:0,complete:false,unlocked:!(o.requires?.length)}]));this.refreshUnlocks();}
 refreshUnlocks(){for(const objective of this.definition.objectives){const state=this.objectives.get(objective.id);state.unlocked=(objective.requires??[]).every((id)=>this.objectives.get(id)?.complete);}}
 apply(event){if(this.status!=='active')return false;let changed=false;for(const definition of this.definition.objectives){const state=this.objectives.get(definition.id);if(state.complete||!state.unlocked)continue;const amount=this.match(definition,event);if(amount<=0)continue;state.progress=Math.min(Math.max(1,Number(definition.amount)||1),state.progress+amount);state.complete=state.progress>=Math.max(1,Number(definition.amount)||1);changed=true;}if(changed){this.refreshUnlocks();if([...this.objectives.values()].every((s)=>s.complete)){this.status='completed';this.completedAt=Date.now();}}return changed;}
 match(objective,event){if(objective.type==='wait'&&event.type==='tick')return Number(event.seconds)||0;if(objective.type!==event.type)return 0;switch(objective.type){case'talk':return event.target===objective.target?1:0;case'collect':return event.itemId===objective.itemId?Number(event.amount)||1:0;case'deliver':return event.itemId===objective.itemId&&event.target===objective.target?Number(event.amount)||1:0;case'reach':return event.zone===objective.zone?1:0;case'interact':return event.target===objective.target?1:0;case'play':case'win':return event.gameId===objective.gameId?1:0;default:return 0;}}
 snapshot(){return Object.freeze({id:this.definition.id,title:this.definition.title,description:this.definition.description??'',status:this.status,startedAt:this.startedAt,completedAt:this.completedAt,objectives:Object.freeze(this.definition.objectives.map((o)=>frozenObjective(o,this.objectives.get(o.id))))});}
 export(){return {id:this.definition.id,status:this.status,startedAt:this.startedAt,completedAt:this.completedAt,objectives:Object.fromEntries([...this.objectives].map(([id,s])=>[id,{...s}]))};}
 import(data={}){this.status=data.status??this.status;this.startedAt=data.startedAt??this.startedAt;this.completedAt=data.completedAt??null;for(const[id,state]of Object.entries(data.objectives??{}))if(this.objectives.has(id))Object.assign(this.objectives.get(id),state);this.refreshUnlocks();}
}
